### ISSUE TITLE
Conf parsing: turn off automagic detection

### ISSUE THREAD

**Issue by rdunklau** [dalibo/pgtoolkit#128]
If a parameter is set as a value in a configuration files while surrounding it with quotes, it should be parsed as a string.
For example, if a GUC contains a version number:

```
some_guc = '2.30`
```

The automagic parsing will return a python float, equal to 2.3.

**Comment by dlax** [comment]
Thanks for the report, I'm removing this surprising behaviour for quoted values in #129.

**Comment by rdunklau** [comment]
Thank you for the quick turnaround !

**Comment by dlax** [comment]
Version 0.31.0 is available with this fixed.
